language: php

sudo: false

php:
  - 5.4
#  - 5.5

env:
  - MAGE=magento-1-9-1-0
#  - MAGE=magento-1-8-1-0
#  - MAGE=magento-1-7-0-2
#  - MAGE=magento-1-6-2-0
#  - MAGE=magento-1-5-1-0

install:
  - mkdir module
  - mv WyWallet module/
  - mv Factoring module/
  - mv GetAddress module/
  - mv Payex module/
  - mv Shared module/
  - mv Autopay module/
  - mv Bankdebit module/
  - mv Payexapi module/
  - mv PartPayment module/
  - mv modman module/
  - mv MasterPass module/
  - cp -f .travis/composer.json composer.json
  - composer install --dev
  - curl https://gordonlesti.com/"$MAGE".tar.gz | tar xz
  - mv $MAGE magento
  - cd magento
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  - cd ..

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `magento`;'
  - mysql -utravis magento < magento/var/magento.sql
  - mysql -e 'create database `magento_test`;'
  - mysql -utravis magento_test < magento/var/magento_test.sql
  - cd magento
  - ls
  - ./modman link ./../module
  - ./modman clone https://github.com/EcomDev/EcomDev_PHPUnit.git
  - cd ..
  - ls

script:
  - php vendor/bin/phpcs --standard=Zend -n module/
  - php vendor/bin/phpmd module/ text codesize,design,unusedcode
  - php vendor/bin/phpcpd module/
  - cd magento && php ../vendor/bin/phpunit --coverage-clover ../build/logs/clover.xml && cd ..

#after_script:
#  - php vendor/bin/coveralls
